services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=mdp123
      - KIBANA_PASSWORD=mdp123
      - LOGSTASH_PASSWORD=mdp123
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./Elasticsearch/elasticserach.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./Elasticsearch/start_and_users.sh:/usr/share/elasticsearch/start_and_users.sh
    command: ["/bin/bash", "/usr/share/elasticsearch/start_and_users.sh"]
    networks:
      - elk
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u elastic:mdp123 https://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  es_data:
  certs:

networks:
  elk:
    driver: bridge
