services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: Elasticsearch
      dockerfile: Dockerfile
    environment:
      - ELASTIC_PASSWORD=mdp123
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data


  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana_pass
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
